"""NED.nl Home Assistant Integration."""
from __future__ import annotations

import logging
import os

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import (
    NedApiClient,
    DEFAULT_QUERIES,
    GRANULARITY_10MIN,
    GRANULARITY_TIMEZONE_AMSTERDAM,
    CLASSIFICATION_CURRENT,
    POINT_NAMES,
    TYPE_NAMES,
)
from .const import DOMAIN, CONF_GRANULARITY, CONF_POINTS

_LOGGER = logging.getLogger(__name__)
PLATFORMS: list[Platform] = [Platform.SENSOR]

_PLACEHOLDER = (
    "# NED.nl Energy Dashboard\n"
    "# This file is auto-generated by the NED.nl integration.\n"
    "# It will be populated with real entity IDs on the next HA restart\n"
    "# after the integration has completed its first setup.\n"
    "title: NED.nl Energy\n"
    "views:\n"
    "  - title: Loading...\n"
    "    path: ned-loading\n"
    "    icon: mdi:loading\n"
    "    cards:\n"
    "      - type: markdown\n"
    "        content: >-\n"
    "          ## NED.nl dashboard is being generated...\n\n"
    "          Restart Home Assistant once after installing the NED.nl\n"
    "          integration to populate this dashboard with live data.\n"
)


def _build_queries(option_points: list[str]) -> list[tuple[int, int, int]]:
    selected = {int(p) for p in option_points}
    filtered = [q for q in DEFAULT_QUERIES if q[0] in selected]
    return filtered or DEFAULT_QUERIES


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Write a placeholder dashboard file early — before Lovelace tries to read it."""
    dashboard_path = hass.config.path("ned_nl_dashboard.yaml")
    if not os.path.exists(dashboard_path):
        try:
            def _write_placeholder():
                with open(dashboard_path, "w", encoding="utf-8") as f:
                    f.write(_PLACEHOLDER)
            await hass.async_add_executor_job(_write_placeholder)
            _LOGGER.info("NED.nl: wrote placeholder dashboard to %s", dashboard_path)
        except OSError as err:
            _LOGGER.warning("NED.nl: could not write placeholder dashboard: %s", err)
    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up NED.nl from a config entry."""
    options = entry.options
    granularity = options.get(CONF_GRANULARITY, GRANULARITY_10MIN)
    point_strings = options.get(CONF_POINTS, ["0"])
    queries = _build_queries(point_strings)

    session = async_get_clientsession(hass)
    client = NedApiClient(
        api_key=entry.data["api_key"],
        session=session,
        granularity=granularity,
        granularity_timezone=GRANULARITY_TIMEZONE_AMSTERDAM,
        classification=CLASSIFICATION_CURRENT,
        queries=queries,
    )

    from .coordinator import NedDataCoordinator
    coordinator = NedDataCoordinator(hass, client)
    await coordinator.async_config_entry_first_refresh()

    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = coordinator
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    # Generate the real dashboard now that sensors are in the entity registry.
    # This file will be read correctly on the next HA restart.
    from .dashboard import async_generate_dashboard
    await async_generate_dashboard(hass, queries)

    entry.async_on_unload(entry.add_update_listener(_async_options_updated))
    return True


async def _async_options_updated(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Reload the integration when options change."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    if unload_ok := await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        hass.data[DOMAIN].pop(entry.entry_id)
    return unload_ok


async def async_remove_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Clean up when the integration is deleted."""
    dashboard_path = hass.config.path("ned_nl_dashboard.yaml")
    try:
        await hass.async_add_executor_job(os.remove, dashboard_path)
        _LOGGER.info("NED.nl: removed dashboard file %s", dashboard_path)
    except FileNotFoundError:
        pass
    except OSError as err:
        _LOGGER.warning("NED.nl: could not remove dashboard file: %s", err)
